version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: greenkeeper-lockfile
          command: yarn global add greenkeeper-lockfile@1
      - run:
          name: Add Yarn global bin to path
          command: echo 'export PATH=$PATH:`yarn global bin`' >> $BASH_ENV
      - run:
          name: greenkeeper-lockfile-update
          command: greenkeeper-lockfile-update
      - run:
          command: yarn --pure-lockfile
      - run:
          name: Test
          environment:
            CIRCLE_TEST_REPORTS: test-results
          command: ember test
      - run:
          name: greenkeeper-lockfile-upload
          command: greenkeeper-lockfile-upload
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  just-test:
    jobs:
      - install
      - test:
          requires:
            - install
