version: 2

jobs:
  install:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install node dependencies
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  just-test:
    jobs:
      - install
      - test:
          requires:
            - install
